config/routes.rb
Rails.application.routes.draw do
  resources :resources
  devise_for :users, controllers: { registrations: "registrations"}

  # device suggestions
  get '/devices/suggest_new' => 'devices#suggest_new'

  resources :addresses, param: :slug
  resources :devices, param: :slug

  get '/devices/:slug/clear_suggestions', to: 'devices#clear_suggestions'
  get '/devices/:slug/driver/:driver_id', to: 'devices#driver'

  get '/admin/clear_database', to: 'admin#clear_database'
  post '/admin/import', to: 'admin#import'
  get '/admin/', to: 'admin#index'

  # contact form
  get '/contact', to: 'contact_us/contacts#new'

  # page routing
  get '/', to: 'high_voltage/pages#show', id: 'root'
  get 'about', to: 'high_voltage/pages#show', id: 'about'

  # XML sitemap
  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap

  # RSS feed
  get '/feed' => 'devices#index', format: "rss"
end

app/models/device.rb
class Device < ApplicationRecord
  has_and_belongs_to_many :address
  has_many :datasheet_suggestions

  before_validation :ensure_has_slug

  scope :suggestions, -> { where(suggestion: true) }
  scope :published, -> { where(suggestion: false) }
  scope :needs_datasheet, -> { where("datasheet = '' OR datasheet IS NULL ") }
  scope :needs_drivers, -> { where("drivers = '[]'") }

  alias_method :old_as_json, :as_json

  def to_amazon_link
    "https://www.amazon.com/s?field-keywords=#{part_number}"
  end

  def to_slug(string)
    string.parameterize.truncate(80, omission: '')
  end

  def to_param
    slug
  end

  def as_json(**args)
    args[:except] = [ "id", "slug", "attribution", "created_at", "updated_at", "suggestion", "views", "scanned" ]
    result = self.old_as_json(args)

    result.delete_if { |key, value| value.nil? || value == ''}

    if self.address.count
      result[:addresses] = self.address.pluck(:address)
    end

    result
  end

private
  def ensure_has_slug
    if slug.nil? || slug.empty?
      self.slug = to_slug(part_number)
    end
  end

  def self.import(csv_file)
    i = 0

    CSV.foreach(csv_file.path) do |row|
      Device.create! manufacturer: row[0], part_number: row[1], friendly_name: row[2]
      i += 1
    end

    return i
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy, :clear_suggestions, :driver ]
  before_action :authenticate_user!, only: [ :new, :edit, :update, :destroy, :clear_suggestions, :driver ]

  # GET /devices
  # GET /devices.json
  def index
    @devices = if params[:q]
                 @is_search = true
                 Device.where("part_number ILIKE '%#{params[:q]}%' OR friendly_name ILIKE '%#{params[:q]}%' OR manufacturer ILIKE '%#{params[:q]}%'").order(part_number: :asc)
               else
                 @is_search = false
                 Device.order(part_number: :asc)
               end

    if user_signed_in? && params[:suggestion]
        @devices = @devices.suggestions
    else
        @devices = @devices.published
    end

    respond_to do |format|
      format.html {
        @devices = @devices.paginate(page: params[:page])
        render :index
      }

      format.json {
        headers['Content-Disposition'] = 'attachment; filename="i2c-devices.json"'
        headers['Content-Type'] ||= 'application/json'
        send_data @devices.to_json, filename: 'devices.json'
      }

      format.cpp {
        headers['Content-Disposition'] = 'attachment; filename="i2c_scanner_devices.cpp'
        headers['Content-Type'] ||= 'text/x-c'
        render 'i2c_scanner_devices.cpp', filename: 'i2c_scanner_devices.cpp'
      }

      format.rss {
        @devices = Device.order(created_at: :desc).limit(20)
        render 'feed', layout: false
      }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    unless user_signed_in?
      @device.update(views: @device.views + 1)
    end
  end

  # GET /devices/new
  def new
    @device = Device.new
    @suggestion = false
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      unless @device.suggestion? || user_signed_in?
        format.html { redirect_to new_user_session_path, notice: 'Not created, user not signed in' }
      else 
        if @device.save
          format.html { redirect_to @device, notice: 'Device was successfully created.' }
          format.json { render :show, status: :created, location: @device }
        else
          format.html { render :new }
          format.json { render json: @device.errors, status: :unprocessable_entity }
        end
      end
    end

    # have to save the device first so that it has an ID and slug - otherwise we can't make a link to it
    if @device.suggestion?
      SuggestionMailer.with(device: @device).new_suggestion.deliver_now
    end

    if @device.datasheet.present?
      @device.datasheet_suggestions.delete_all
    end
  end

  # POST /devices/suggest
  # POST /devices.json
  def suggest_new
    @device = Device.new
    @suggestion = true

    respond_to do |format|
      format.html { render :new, notice: 'Enter device details' }
    end
  end

  def suggest_create
    @device = Device.new(device_params, suggestion: true)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def driver
    driver = DatasheetSuggestion.find params[:driver_id]
    @device.drivers.push({ title: driver.title, link: driver.link})
    @device.save

    driver.delete

    redirect_back fallback_location: device_path(@device)
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def clear_suggestions
    @device.datasheet_suggestions.delete_all
    redirect_to '/admin'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find_by slug: params[:slug]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:part_number, :friendly_name, :addresses, :manufacturer, :suggestion, :obsolete, :datasheet, :adafruit, :sparkfun, :amazon, :release_date, :is_5v, :is_3v, :is_standard_speed, :is_full_speed, :is_fast_speed, :is_high_speed, :is_ultra_fast_speed, :is_spi, address_ids: [])
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_with(model: device, local: true) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if @suggestion %>
<p>Please enter as much information as you have about the device. After you submit it, we will review it and add it to the directory as appropriate.</p>
<%= form.hidden_field :suggestion, value: 1 %>
<% end %>

  <div class="field form-group">
    <%= form.label :part_number %>
    <%= form.text_field :part_number, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :friendly_name %>
    <%= form.text_field  :friendly_name, class: 'form-control'  %>
  </div>

  <div class="field form-group">
    <%= form.label :manufacturer %>
    <%= form.text_field :manufacturer, class: 'form-control'  %>
  </div>

  <div class="form-check">
    <%= form.check_box :obsolete, class: 'form-check-input' %>
    <%= form.label 'Obsolete?', class: 'form-check-label' %>
  </div>  

  <div class="form-check">
    <%= form.check_box :is_spi, class: 'form-check-input'  %>
    <%= form.label 'SPI?', class: 'form-check-label'  %>
  </div>  

  <div class='form-check form-check-inline'>
    <%= form.label '3V?', class: 'form-check-label' %>
    <%= form.check_box :is_3v, class: 'form-check-input'  %>
  </div>  

  <div class='form-check form-check-inline'>
    <%= form.label '5V?', class: 'form-check-label' %>
    <%= form.check_box :is_5v, class: 'form-check-input'  %>
  </div>  

  <div class="field form-group">
    <%= form.label :datasheet %>
    <%= form.text_field :datasheet, class: 'form-control'  %>
  </div>

  <% if @device.datasheet_suggestions.where(kind: 'datasheet').count > 0 %>
  <h5>Suggested datasheets</h5>
  <ul>
    <% @device.datasheet_suggestions.where(kind: 'datasheet').each do |datasheet| %>
    <li><%= button_tag "Use", type: 'button', class:'btn btn-info', onclick: "useDatasheet('#{datasheet.link}')" %>
      <%= datasheet.title %> - <a href="<%= datasheet.link %>" target="_blank"><%= datasheet.link %></a></li>
    <% end %>
    </ul>
    <hr>
    <% end %>

  <% if @device.drivers.length > 0 %>
    <ul>
    <% @device.drivers.each do |driver| %>
      <li><%= link_to driver['title'], driver['link'] %></li>
    <% end %>
    </ul>
  <% end %>

  <% if @device.datasheet_suggestions.where(kind: 'driver').count > 0 %>
  <h5>Suggested Drivers</h5>
  <ul>
    <% @device.datasheet_suggestions.where(kind: 'driver').each do |datasheet| %>
    <li><%= link_to button_tag("Add driver", type: 'button', class:'btn btn-info'), "#{device_path(@device)}/driver/#{datasheet.id}" %>
      <%= datasheet.title %> - <a href="<%= datasheet.link %>" target="_blank"><%= datasheet.link %></a></li>
    <% end %>
    </ul>
    <hr>
  <% end %>

  <div class="field form-group">
    <%= form.label :adafruit %>
    <%= form.text_field :adafruit, class: 'form-control'  %>
  </div>

  <div class="field form-group">
    <%= form.label :sparkfun %>
    <%= form.text_field :sparkfun, class: 'form-control'  %>
  </div>

  <div class="field form-group">
    <%= form.label :amazon %>
    <%= form.text_field :amazon, class: 'form-control'  %>
  </div>

  <div class="field form-group">
    <%= form.label "Release year" %>
    <%= form.number_field :release_date, class: 'form-control', min: 1982, max: 2025 %>
  </div>


  <div class="field form-group">
    <%= form.label 'I2C Addresses' %><br/>
    <%= form.collection_check_boxes :address_ids, Address.where(reserved: false).order(address: :asc), :id, :to_s, class: 'form-check-inline'  do |b|
	b.label(class: "form-check-label-inline") { (b.text + ' ' + b.check_box(class: "form-check-inline")).html_safe }
	end
	%>
  </div>

<% if user_signed_in? %>
  <div class="field form-group">
    <%= form.label 'Suggestion' %>
    <%= form.check_box :suggestion, class: 'form-control' %>
  </div>
<% end %>

  <div class="actions">
    <button type="submit" class="btn btn-primary">Update Device</button>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

<% content_for :page_title, "edit #{@device.part_number} | I2C Device Directory" %>

app/views/devices/i2c_scanner_devices.cpp.erb
#include "i2c_scanner.h"

/*
 * This file is automatically generated by https://i2cdevices.org/
 *
 * Generated <%= Time.now.to_s %>
 *
 * It's intended to be used by the ESP diagnostic tool at
 * https://github.com/romkey/ESP-Diagnostic-Tool
 *
 * To update the known device list in the diagnostic tool,
 * generate a new version of this file, copy it to the src
 * directory and rebuild the tool.
 *
 * The MIT License (MIT)
 * Copyright © <%= Time.now.year %> John Romkey <romkey@romkey.com>
 * 
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the “Software”), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions: The above
 * copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

i2c_device_t i2c_scanner_known_devices[] = {
<% @devices.each do |device| %>
  <% if device.address.count > 0 %>
 { "<%= device.part_number %>", "<%= device.friendly_name %>", (const byte *)"<%= device.address.map { |addr| "\\x%02x" % addr.address }.join('') %>" },
   <% end %>
<% end %>
};

int i2c_scanner_known_devices_length = sizeof(i2c_scanner_known_devices)/sizeof(i2c_device_t);

app/views/devices/index.html.erb
<h1>I2C Device List <%= link_to(fa_icon('rss'), '/devices.rss') %></h1>

<p>
<%= link_to 'Suggest a device', '/devices/suggest_new', class: 'btn btn-primary btn-success' %>
<%= link_to 'Download as JSON', '/devices.json', class: 'btn btn-primary' %>
<%= link_to 'Download I2C Scanner C++ code ', '/devices.cpp', class: 'btn btn-primary' %>
</p>

<table class='table table-striped'>
  <thead class='thead-light'>
    <tr>
      <th>Part</th>
      <th>Description</th>
      <th>Manufacturer</th>
      <th>Addresses</th>

      <th>Datasheet</th>
      <th>Adafruit</th>
      <th>Sparkfun</th>
      <th>Amazon</th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <th scope='row'><%= link_to device.part_number, device %></th>
        <td><%= device.friendly_name %></td>
	<td><%= device.manufacturer %></td>
	<% if device.address.length == 0 %>
	  <td>none</td>
	<% elsif device.address.length == 1 %>
          <td><%= link_to device.address.first.to_s, device.address.first %></td>
	<% elsif device.address.length == 2 %>
          <td><%= link_to device.address.first.to_s, device.address.first %>, <%= link_to device.address.second.to_s, device.address.second %></td>
	<% else %>
	  <td><%= link_to device.address.length, device %></td>
	<% end %>
	<% if device.datasheet.present? %>
          <td><%= link_to fa_icon('table', class: 'fa-2x'), device.datasheet %></td>
	<% else %>
	  <td></td>
	<% end %>
	<% if device.adafruit.present? %>
          <td><%= link_to image_tag('Adafruit-logo-64x64.png', size: '32', alt: 'See device on Adafruit'), device.adafruit %></td>
	<% else %>
	  <td></td>
	<% end %>
	<% if device.sparkfun.present? %>
          <td><%= link_to image_tag('Sparkfun-logo-64x64.png', size: '32', alt: 'See device on Sparkfun'), device.sparkfun %></td>
	<% else %>
	  <td></td>
	<% end %>
	<% if device.amazon.present? %>
          <td><%= link_to image_tag('Amazon-logo-64x64.png', size: '32', alt: 'See device on Amazon'), device.amazon %></td>
	<% else %>
          <td><%= link_to image_tag('Amazon-logo-64x64.png', size: '32', alt: 'See device on Amazon'), device.to_amazon_link %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'New Device', new_device_path %>
<% end %>

<%= will_paginate @devices %>

<% content_for :page_title, 'List of I2C Devices' %>
<% content_for :page_description, "List of I2C/TwoWire Devices and their addresses" %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<div class='card'>
  <div class="card-body">
    <h1 class='card-title'><%= @device.part_number %></h1>
<% if @device.manufacturer.present? %>
    <div class='card-subtitle'><h2 class='card-title'><%= @device.manufacturer %></h2></div>
<% end %>
    <div class='card-subtitle'><h3 class='card-title'><%= @device.friendly_name %></h3></div>

<% if @device.suggestion? %>
  <strong>SUGGESTION</strong>
<% end %>

<% if @device.release_date %>
<p class='card-text'>    
  Release year: <%= @device.release_date %>
</p>
<% end %>

<p class='card-text'>
  <b>Always confirm information before making software, design or purchasing decisions.</b>
</p>

<% if @device.is_3v || @device.is_5v || @device.is_spi %>
<p class='card-text'>    
  <% if @device.is_spi %>
    ✅SPI  
  <% end %>
  <% if @device.is_3v %>
    ✅3V  
  <% end %>
  <% if @device.is_5v %>
    ✅5V  
  <% end %>
</p>
<% end %>

<% if @device.datasheet.present? %>
    <p class='card-text'> 
      Datasheet:  <%=link_to  @device.datasheet, @device.datasheet %>
    </p>
<% end %>

<% if @device.adafruit.present? %>
    <p class='card-text'> 
      Adafruit: <%= link_to @device.adafruit, @device.adafruit %>
    </p>
<% end %>

<% if @device.sparkfun.present? %>
    <p class='card-text'> 
      Sparkfun: <%= link_to @device.sparkfun, @device.sparkfun %>
    </p>
<% end %>

    <p class='card-text'> 
      <%= link_to "Search Amazon for #{@device.part_number}", @device.to_amazon_link %>
    </p>

<% if @device.drivers.length > 0 %>
<h3>Drivers and resources</h3>
<ul>
    <% @device.drivers.each do |driver| %>
      <li><%= link_to driver['title'], driver['link'] %></li>
    <% end %>
</ul>
<% end %>

    <p class='card-text'>
      <h2 class='card-title'>Addresses:</h2
      <ul class="list-unstyled">
	<% @device.address.order(address: :asc).each do |addr|  %>
	<li><%= link_to("0x%02x" % addr.address, addr) %></li>
	<% end %>
      </ul>
    </p>

    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_device_path(@device), class: 'btn btn-info' %> <%= link_to 'Delete', device_path(@device), method: :delete, class: "btn btn-danger",  data: {confirm: "Are you sure?"} %>
    <% end %>

  </div>
</div>


<% content_for :page_title, "#{@device.part_number} | I2C Device Directory" %>
<% content_for :page_description, "#{@device.part_number}: #{@device.friendly_name}, I2C/TwoWire addresses: #{@device.address.map { |addr| addr.to_s }.join(', ') }" %>