config/routes.rb
Rails.application.routes.draw do
  resources :resources
  devise_for :users, controllers: { registrations: "registrations"}

  # device suggestions
  get '/devices/suggest_new' => 'devices#suggest_new'

  resources :addresses, param: :slug
  resources :devices, param: :slug

  get '/devices/:slug/clear_suggestions', to: 'devices#clear_suggestions'
  get '/devices/:slug/driver/:driver_id', to: 'devices#driver'

  get '/admin/clear_database', to: 'admin#clear_database'
  post '/admin/import', to: 'admin#import'
  get '/admin/', to: 'admin#index'

  # contact form
  get '/contact', to: 'contact_us/contacts#new'

  # page routing
  get '/', to: 'high_voltage/pages#show', id: 'root'
  get 'about', to: 'high_voltage/pages#show', id: 'about'

  # XML sitemap
  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap

  # RSS feed
  get '/feed' => 'devices#index', format: "rss"
end

app/views/resources/_form.html.erb
<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resources</h1>

<table>
  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= link_to resource.title, resource.link %></a></td>
	<% if user_signed_in? %>
	<td><%= link_to 'edit', edit_resource_path(resource) %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Resource', new_resource_path %>
<% end %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @resource.link %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>