config/routes.rb
Rails.application.routes.draw do
  resources :resources
  devise_for :users, controllers: { registrations: "registrations"}

  # device suggestions
  get '/devices/suggest_new' => 'devices#suggest_new'

  resources :addresses, param: :slug
  resources :devices, param: :slug

  get '/devices/:slug/clear_suggestions', to: 'devices#clear_suggestions'
  get '/devices/:slug/driver/:driver_id', to: 'devices#driver'

  get '/admin/clear_database', to: 'admin#clear_database'
  post '/admin/import', to: 'admin#import'
  get '/admin/', to: 'admin#index'

  # contact form
  get '/contact', to: 'contact_us/contacts#new'

  # page routing
  get '/', to: 'high_voltage/pages#show', id: 'root'
  get 'about', to: 'high_voltage/pages#show', id: 'about'

  # XML sitemap
  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap

  # RSS feed
  get '/feed' => 'devices#index', format: "rss"
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.order(address: :asc)
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    unless user_signed_in?
      @address.update(views: @address.views + 1)
    end
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find_by slug: params[:slug]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:address, :reserved)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.number_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>I2C Address List</h1>

<table class='table table-striped'>
  <thead class='thead-light'>
    <tr>
      <th>Address</th>
      <th>Devices</th>
      <th>Reserved</th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <% if address.reserved? || address.device.count > 0 %>
      <tr>
        <th scope="row"><%= link_to("0x%02x" %address.address, address) %></th>
	<td>
	  <% address.device.published.map do |device| %>
	     <%= link_to(device.part_number, device) %> 
	   <% end %>
	</td>
	<td>
	  <% if address.reserved? %>
	  ✔
	  <% end %>
	</td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>


<% if user_signed_in? %>
<%= link_to 'New Address', new_address_path %>
<% end %>

<% content_for :page_title, 'List of I2C Addresses' %>
<% content_for :page_description, "List of I2C/TwoWire addresses and devices using them" %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<div class='card'>
    <div class="card-body">
    <h1 class='card-title'>I2C Address <%="0x%02x" % @address.address %></h1>
    <div class='card-subtitle'><%= @address.device.count == 0 ? "No" : @address.device.count %> known devices at this address</div>

    <p class='card-text'>
      <h2 class='card-title'>Devices:</h2>
      <ul class="list-group">
	<% @address.device.published.order(part_number: :asc).each do |device|  %>
  	  <li class="list-group-item">
	    <%= link_to(device.part_number, device) %> - <%= device.friendly_name %>
	  </li>
	<% end %>
      </ul>
    </p>
</div>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_address_path(@address) %>
<% end %>

<% content_for :page_title, "I2C Address #{@address.to_s} | I2C Device Directory" %>
<% content_for :page_description, "#{@address.to_s}: I2C/TwoWire addresses, devices: #{@address.device.map { |dev|dev.part_number }.join(', ') }" %>