config/routes.rb
Rails.application.routes.draw do
  resources :resources
  devise_for :users, controllers: { registrations: "registrations"}

  # device suggestions
  get '/devices/suggest_new' => 'devices#suggest_new'

  resources :addresses, param: :slug
  resources :devices, param: :slug

  get '/devices/:slug/clear_suggestions', to: 'devices#clear_suggestions'
  get '/devices/:slug/driver/:driver_id', to: 'devices#driver'

  get '/admin/clear_database', to: 'admin#clear_database'
  post '/admin/import', to: 'admin#import'
  get '/admin/', to: 'admin#index'

  # contact form
  get '/contact', to: 'contact_us/contacts#new'

  # page routing
  get '/', to: 'high_voltage/pages#show', id: 'root'
  get 'about', to: 'high_voltage/pages#show', id: 'about'

  # XML sitemap
  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap

  # RSS feed
  get '/feed' => 'devices#index', format: "rss"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title><%= yield(:page_title) %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="Content-Language" content="en">
<meta name="google-site-verification" content="xlJluXkyUnbXOykFmQ6hwwfRdQWuZCYvKeiny4K0F4I">
<meta name="Description" content="<%= yield :page_description %>">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= auto_discovery_link_tag :rss, devices_url(:format => :rss) %>
</head>

<body>
<div class='container'>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">I2C Devices</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
    <%= link_to 'I2C Devices', devices_path, class: 'nav-link' %>
    </li> 
    <li class="nav-item">
    <%= link_to 'I2C Addresses', addresses_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
    <%= link_to 'I2C Resources', resources_path, class: 'nav-link' %>
    </li>
    <% if Rails.env.development? %>
    <li class="nav-item">
    <%= link_to 'Clear database', '/admin/clear_database', class: 'nav-link' %>
    </li>
    <% end %>
    <% if user_signed_in? %>
    <%= link_to 'Admin', '/admin', class: 'nav-link' %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link'  %>
    <% end %>
  </ul>
  <form class="form-inline my-2 my-lg-0" action="/devices">
  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</div>
</nav>

<% if notice %>
<div class="alert alert-primary" role="alert">
  <p id="notice"><%= notice %></p>
</div>
<% end %>

<%= yield %>

</div>
<footer>
<div class='container'>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
    <%= link_to 'About', '/about', class: 'nav-link' %>
    </li> 
    <li class="nav-item">
    <%= link_to 'Contact', '/contact', class: 'nav-link' %>
    </li> 
    <li class="nav-item">
    <%= link_to 'Source Code', 'https://github.com/romkey/I2C-Directory', class: 'nav-link' %>
    </li>
    <li class="nav-item">
    <%= link_to 'ESP8266/ESP32 I2C Scanner', 'https://github.com/romkey/ESP-Diagnostic-Tool', class: 'nav-link' %>
    </li>
  </ul>
</div>
</nav>
</footer>
</body>
</html>

<% content_for :page_title, "I2C Device Directory" %>